[project]
name = "cvhub-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "config>=0.5.1",
    "flagembedding>=1.4.2",
    "hf>=1.31.0",
    "jieba>=0.42.1",
    "keybert>=0.9.0",
    "nltk>=3.10.3",
    "numpy>=2.5.3",
    "psycopg2>=2.9.13",
    "rank-bm25>=0.2.2",
    "rapidfuzz>=3.14.6",
]
